### ISSUE TITLE
Uploading multiple files doesn't work correctly

### ISSUE THREAD

**Issue by tmarciszewski** [JonRowe/phoenix_live_view_dropzone#17]
I've noticed that uploading multiple files (3 or more) produces random results. Not all files are getting uploaded. The more files you try to upload at once the bigger the chance that some of them don't trigger and are not uploaded. I think it may be connected with the way information about upload id and URL are passed back to the module.

Can you point me in the direction of how to disable multiple file upload? For now I'll be completely happy just uploading single file and using fork of the lib. It may also result in later PR for multi/single file upload for the library.

**Comment by JonRowe** [comment]
Can you check out the `pin-to-single-file` branch? Its the start of an option to force one file at a time, the caveat I think where it won't work is drag'n'drop because its always possible to drop multiple files, so someone would have to write a custom decoder to not, you can either fork from there but I'd be happy if you wanted to help get that option finished and released.

**Comment by tmarciszewski** [comment]
I didn't think about the issue with drag and drop :( Maybe if this option is enabled we should take only first dropped file and disregard the rest?

**Comment by JonRowe** [comment]
It might be possible to do something there, happy for it be expanded upon if you have some time?

**Comment by JonRowe** [comment]
:wave: I'm archiving this project as I feel LiveViews own file upload solutions would be better supported
